### ISSUE TITLE
unable to connect my storage

### ISSUE THREAD

**Issue by JOduMonT** [nextcloud/integration_openproject#201] opened 2022-08-16 08:28 UTC
### environment
- nextcloud: 23, latest, stable
  - plugin: 2.0.0
- openproject:  12.1.6
-----
In the OpenProject plugin integration, it is mentioned to find my OpenProject OAuth settings in Administration > File storage as an Administrator.
While even if I click on the link or follow the instruction I don't find the storage section.

> [Error 500] An error occurred on the page you were trying to access. If you continue to experience problems please contact your Project administrator for assistance.

- The storage plugin seams to be by default
![image](https://user-images.githubusercontent.com/5204724/184834092-763e94ba-9ecd-4fe9-9047-9e6e435b5996.png)

- but it don't appear under setting
![image](https://user-images.githubusercontent.com/5204724/184833974-854d65ec-5de0-49af-92e3-48cd13955ada.png)

**Comment by SwikritiT** [comment] 2022-08-16 09:40
Hi, As mentioned here https://www.openproject.org/docs/user-guide/nextcloud-integration/ 
`The integration is available starting with Nextcloud 22 and OpenProject 12.2.` 
Can you upgrade your open project and try again

**Comment by cmmata** [comment] 2022-08-17 09:37
I am also having problems connecting my Nextcloud and Openproject instances. I have Nextcloud 24.0.4 and OpenProject 12.2.0. The setup in Openproject is done, but going to Nextcloud to get the clientId and secret, it says `No OpenProject detected at the URL✖` when introducing OP's URL. I am copying and pasting the URL of the OP instance, so no wrong input there.

Both instances are in the same server, and if I call a `curl` to the openproject URL from the server's console, the HTML received is OP homepage, so the server name is resolving correctly.

What else can be wrong?

**Comment by individual-it** [comment] 2022-08-18 07:51
@cmmata could you do a curl request to `http://<your-openproject-url>/api/v3/` and send the reply?

**Comment by cmmata** [comment] 2022-08-18 08:11
The URL is in https, but here is the reply

```json
{
  "_type": "Root",
  "instanceName": "OpenProject",
  "coreVersion": "12.2.0",
  "_links": {
    "self": {
      "href": "/api/v3"
    },
    "configuration": {
      "href": "/api/v3/configuration"
    },
    "memberships": {
      "href": "/api/v3/memberships"
    },
    "priorities": {
      "href": "/api/v3/priorities"
    },
    "relations": {
      "href": "/api/v3/relations"
    },
    "statuses": {
      "href": "/api/v3/statuses"
    },
    "time_entries": {
      "href": "/api/v3/time_entries"
    },
    "types": {
      "href": "/api/v3/types"
    },
    "user": {
      "href": "/api/v3/users/3",
      "title": "Carles Mata"
    },
    "userPreferences": {
      "href": "/api/v3/users/3/preferences"
    },
    "workPackages": {
      "href": "/api/v3/work_packages"
    }
  }
}
```

**Comment by individual-it** [comment] 2022-08-18 08:18
@cmmata that looks correct and good
if you are using both on `localhost` you might have to set NextCloud to accept `localhost` as "remote servers"
you can do that with the occ command, in the nextcloud install directory run `php occ config:system:set allow_local_remote_servers --value 1`

**Comment by cmmata** [comment] 2022-08-18 09:32
@individual-it that works! Thank you! 😄

It's a bit weird because I don't use `localhost` on any service. I have a local DNS to resolve server names with the local network, and the domain DNS to have those server names available from outside. But looks like Nextcloud is detecting somehow that the servers are local.

Anyway, it's working for me, so if the problem is solved also for @JOduMonT, we could close this issue.

Thanks again for the quick support!

**Comment by individual-it** [comment] 2022-08-18 09:50
I'm not sure what NC is checking with that setting, but happy it works. closing this issue then

**Closed by individual-it** 2022-08-18 09:50 UTC

**Comment by Kharonus** [comment] 2022-08-18 11:39
Ahoi @cmmata 
even if routed through a local DNS or a reverse proxy, the NC detects that it is in the end a local request. Same as @individual-it, I cannot say where this option is checked or why it is prevented without it. But I, too, have to set this before my setup (I have both, NC and OP running in docker, together with a traefik proxy to resolve the host names) works.
